# Assumes all service accounts have root access
#   Configure via: `kubectl create clusterrolebinding serviceaccounts-cluster-admin   --clusterrole=cluster-admin   --group=system:serviceaccounts`
#
# After applying run `kubectl get secret/contourguessr-gha-secret -n contourguessr -o yaml` and copy the result into
#   the GitHub secret K8S_SECRET
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contourguessr-gha
  namespace: contourguessr
---
apiVersion: v1
kind: Secret
metadata:
  name: contourguessr-gha-secret
  namespace: contourguessr
  annotations:
    kubernetes.io/service-account.name: contourguessr-gha
type: kubernetes.io/service-account-token
