name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Download data
        run: aws s3 sync s3://contourguessr-data ./data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - uses: docker/build-push-action@v3
        name: Build and push the docker image
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dzfranklin/contourguessr-api:latest
            ghcr.io/dzfranklin/contourguessr-api:${{ github.run_number }}_${{ github.run_attempt }}
          cache-from: type=gha
          cache-to: type=gha
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p "$HOME/.kube"
          echo $KUBECONFIG | tr -d '[:space:]' | base64 --decode > "$HOME/.kube/config"

      - uses: actions/checkout@v4

      - name: Deploy to k8s
        uses: azure/k8s-deploy@v1
        with:
          namespace: contourguessr
          manifests: |
            infra/deployment.yaml
          images: |
            ghcr.io/dzfranklin/contourguessr-api:${{ github.run_number }}_${{ github.run_attempt }}
