name:
  deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Download data
        run: aws s3 sync s3://contourguessr-data ./data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - uses: docker/build-push-action@v3
        name: Build and push the docker image
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/contourguessr-api:latest
            ghcr.io/${{ github.repository_owner }}/contourguessr-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
